name: Check if the CHANGELOG.md has been updated

on: [pull_request]

jobs:
  check:
    name: Test on ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checking the CHANGELOG.md has been updated in this PR
      continue-on-error: true
      run: |
        set -e
        git fetch origin ${{ github.base_ref }}
        git diff --name-only origin/${{ github.base_ref }} | grep -q CHANGELOG.md
